### ISSUE TITLE
More than 2 recipients

### ISSUE THREAD

**Issue by adrienmaloba** [jasonmunro/cypht#377] opened 2020-02-20 08:26 UTC
##  Enhancement

When there are more than 3 recipients, one disappears.

![cypht_recipients_3_2](https://user-images.githubusercontent.com/28392444/74914489-32903700-53cb-11ea-8530-cade5f31fda2.gif)

**Comment by marclaporte** [comment] 2020-02-20 23:42
Good catch!

**Comment by jasonmunro** [comment] 2020-03-02 21:03
Yikes! Thanks for the report. Hopefully won't be hard to track down and fix.

**Comment by marclaporte** [comment] 2020-03-13 22:07
@jasonmunro our team will handle so you focus on bigger things :-)

**Comment by jasonmunro** [comment] 2020-04-16 02:12
I merged the PR for this without looking close enough and it broke address parsing. Not sure what is going on here as I can't even reproduce the original bug locally yet. I'm reverting that PR and I will see if I can trigger the issue and fix it.

**Comment by jasonmunro** [comment] 2020-04-16 03:06
Found a message that triggered this, and it would appear the issue is a trailing newline. If the last value on a header is an E-mail address, the validation fails because the newline is not stripped off, causing it to be dropped from the reply-all list.

I pushed a fix to master, would be great if someone could confirm it works for them now!

**Comment by adrienmaloba** [comment] 2020-04-16 22:04
I'll test for confirmation.

**Comment by marclaporte** [comment] 2020-04-17 17:33
On our Intranet, I updated from "1769ba9b8f19f69caa01cae4a9c8af5da06367ec" to "beea64a80974445b0400be9a76935b4d9360626b" and I confirm the fix.

**Closed by marclaporte** 2020-04-17 17:33 UTC
Labels: bug, smtp
