### ISSUE TITLE
Compose interface: unable to select sender 

### ISSUE THREAD

**Issue by jmce** [jasonmunro/cypht#139] opened 2016-10-15 17:37 UTC
Under the same configuration and test account in which I noticed my previously submitted issues, I had these problems with sender selection:
1. With no additional IMAP & SMTP accesses defined (only the initial ones for the account), I specified info and saved it.  Then, when trying to compose a message, the sender profile selector (below the message body field) had no options to select, and sending was refused. If I remember it correctly, this was not happening before I edited/saved profile info.  After logging out and logging in again, the selector was again correctly showing the single available profile.  Another user (in a different account) met the same problem, again solved by logging out/in.
2. Later I added two additional IMAP server entries in my test account:
   - one for the same local server, for access to a different local account;  
   - one for access to an account in a separate, remote, IMAP server.
   
   IMAP access to both seems OK, and I noticed that two additional profiles had been created. But, when trying to compose a new message, the sender selection list still has only one entry: the one for the base account. Unlike above, logging out doesn't fix this. 

In that second case I added no SMTP servers, but my Postfix configuration would allow the 'base' logged-in user to use his default SMTP connection to send email as another local user.
This should often not be the case, of course, but can be a reasonable configuration choice in tiny orgs and personal servers with multiple accounts.   I haven't yet seen if having additional SMTP server entries in the cypht interface somehow helps to solve this sender selection issue (but the available interfaces suggest that one SMTP server entry may be used in more than one profile).
#### Version info:

cypht master.zip files from 2016-10-12 14:48:18 +0000 on Debian Jessie [8.6] with
- memcached 1.4.21-1.1
- php-memcached 2.2.0-2
- nginx-… 1.9.10-1~bpo8+3
- php5-…  5.6.26+dfsg-0+deb8u1 (using php5-fpm)
- postfix-… 2.11.3-1
- dovecot-… 1:2.2.24-1~bpo8+1 [using sdbox as mailbox format]
- openssl 1.0.2j-1~bpo8+1
- libssl1.0.0  1.0.2j-1~bpo8+1

**Comment by jasonmunro** [comment] 2016-10-15 21:05
Thank you for the detailed report (and the other very well written issues)! Your feedback is greatly appreciated. I'm busy hosting family this weekend so I won't have a chance to really dig in just yet. I will do so for this, and the other issues you raised, as soon as I can (probably on Monday).

Your willingness to provide feedback helps make the project better, so thanks again for taking the time to do so!

**Comment by jasonmunro** [comment] 2016-10-17 20:43
I don't like the way I implemented profiles. The code is ugly and obviously buggy. You also raise a valid point WRT identity restrictions or the lack thereof. We have also received a request to decouple profiles so a user with multiple local addresses in a catch-all account can properly manage their identities.

I'm going to see what I can do to clean things up. I will let you know when I have something worth testing.

**Comment by jasonmunro** [comment] 2016-10-17 22:20
> With no additional IMAP & SMTP accesses defined (only the initial ones for the account), I specified 
> info and saved it. Then, when trying to compose a message, the sender profile selector (below the 
> message body field) had no options to select, and sending was refused. If I remember it correctly, this 
> was not happening before I edited/saved profile info. After logging out and logging in again, the 
> selector was again correctly showing the single available profile. Another user (in a different account) 
> met the same problem, again solved by logging out/in.

Confirmed this bug. It's actually a problem with the SMTP module set. I should have a fix for this today or tomorrow.

**Comment by jasonmunro** [comment] 2016-10-18 17:11
Issue number 1 should be resolved now. When saving data between logins, we strip out default servers. There is no reason to save those since they are repopulated at login. The bug was we were not restoring them for the current session (save but no logout). I added code to do so and it seems to resolve this.

Issue number 2 and your other observations will require more thought :) The code should be restricting one SMTP server to one profile, and as you noticed profiles are available for any IMAP or POP3 account you have. I'm not sure if this is the right way to organize this, so I'm rethinking these relationships. Any suggestions are welcome!

**Comment by jmce** [comment] 2016-10-18 17:29
Thank *you* for cypht, and for such a kind & prompt response on these issues. :)

I have a few notes on interfaces & configuration, maybe including suggestions on what would be nice to have (as an user) re profiles/servers/accounts — been busy with other work, but I hope to be able to submit those here tomorrow (and to resume testing).

**Comment by dumblob** [comment] 2016-10-18 17:54
>Issue number 2 and your other observations will require more thought :) The code should be restricting one SMTP server to one profile, and as you noticed profiles are available for any IMAP or POP3 account you have. I'm not sure if this is the right way to organize this, so I'm rethinking these relationships. Any suggestions are welcome!

I'm not sure if I understand the question well enough. Are you asking about the main shortcomings and benefits of using either of the following?

1. One Cypht account having one and only one IMAP/POP3 server and one and only one SMTP server.

1. One Cypht account having more than one IMAP/POP3 server and more than one SMTP servers.

**Comment by jasonmunro** [comment] 2016-11-30 22:20
Found and fixed another bug with profiles and smtp servers, so just a heads up to pull the latest on this. I'm still pondering how I want to redesign profiles. Seems to be a pain point for a lot of new users.

**Closed** 2017-02-26 21:32 UTC
Labels: bug, imap, smtp
