### ISSUE TITLE
Add Alias Suppport

### ISSUE THREAD

**Issue by cwmke** [jasonmunro/cypht#131] opened 2016-10-05 21:09 UTC
For an example, I own the domain example.com. I use different addresses on different websites such as github@example.com for github and google@example.com for Google. What I think would be great to have is the ability to either automatically detect the correct address based on the To field while replying and/or to allow for multiple profiles to be setup with different addresses and signatures. Most websites don't need responses so multiple profiles would be a fine improvement on this itself. 

Thanks for any considerations and for the wonderful client!

**Comment by jasonmunro** [comment] 2016-10-06 17:33
Thanks for the feedback! We do have a profiles module set, but it only allows one identity for each E-mail account you have configured. The compose page will automatically detect the correct SMTP server to reply with based on the TO: filed when replying (using the profiles). I think I can decouple this such that you could have multiple profiles associated with a single account. I will check into it!

**Comment by jasonmunro** [comment] 2017-02-26 21:35
This is sort of a duplicate of this: https://github.com/jasonmunro/cypht/issues/152 so I'm closing this and will update the other issue when I have something to report.

**Closed by jasonmunro** 2017-02-26 21:35 UTC
Labels: profiles
