### ISSUE TITLE
[Bug] When showing Messages inline - All Headers are shown on next Auto-Refresh

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#219] opened 2017-08-25 10:05 UTC
When showing Messages inline - All Headers are shown on next Auto-Refresh

1. Enable inline-messages
2. open a Message
3. Wait for next Autorefresh
4. Full Header-Details are shown for open EMail

In other news: An inline EMail stays open after delete - and sometimes cant be closed anymore. Opening another EMail solves this.

1. Inline-open an EMail
2. Delete it
3. EMail stays open
4. ...
5. EMail can't be closed anymore (missing x/not working x)

And another: Inline Message-Display has no option to add to the Address Book.

Revision: [5f2d5c5f8e2f9083c84d795b8337ffc403eab42f](https://github.com/jasonmunro/cypht/commit/5f2d5c5f8e2f9083c84d795b8337ffc403eab42f)

<3

**Comment by jasonmunro** [comment] 2017-08-25 15:50
confirmed. There is also a bug with the unread count when using inline message view I need to fix. This is specific to the inline message style of "lnline", the "right" style works correctly. I will update this issue when I have a fix. Thanks for the report.

**Comment by jasonmunro** [comment] 2017-08-28 22:52
FYI, This is turning out to be tricky to fix :) I might have to disable the "inline" style until I come up with something.

**Comment by jasonmunro** [comment] 2017-09-21 22:18
Pushed some fixes for this. All header display behavior is fixed, unread count is also fixed, and the cached mailbox state should also be corrected. Let me know if you get a chance to retest and how it goes! Thanks

**Comment by jasonmunro** [comment] 2017-09-26 15:23
@ulfgebhardt I'm going to close this because I think it's resolved. If you find issues please re-open. Thanks!

**Closed by jasonmunro** 2017-09-26 15:23 UTC
Labels: bug, inline_message

**Comment by ulfgebhardt** [comment] 2017-09-27 22:09
Confirm fix, thanks alot!
