### ISSUE TITLE
A log out button, please

### ISSUE THREAD

**Issue by dunstn** [jasonmunro/cypht#295] opened 2018-10-26 06:34 UTC
Hi,
I've downloaded the last version of Cypht, and I think, that a Log out button would be very useful. To log out now, one needs to check every menu, until you find it in the Settings->Save menu. It would be very user-friendly to create  a separate, Log out button below the menus or a main menu item in the bottom.
Thanks
Dunstn

**Comment by jasonmunro** [comment] 2018-10-26 14:13
@dunstn - there should be a logout button at the bottom of the main menu already, do you not have one?

![menu](https://user-images.githubusercontent.com/3793556/47571905-4c1c8e00-d8ff-11e8-8855-ed731b750c90.png)

**Comment by dunstn** [comment] 2018-10-26 15:48
Oh, sorry. My Cypht was mistakenly set up in Debug mode.  I have found the Logout button after I corrected my setup. Did you have any reason not to make a Logout button in Debug mode?

**Comment by jasonmunro** [comment] 2018-10-26 15:56
The logout button should be present with or without debug mode. For me the Main menu section is identical regardless of debug mode.

**Comment by jasonmunro** [comment] 2018-11-15 19:35
I cannot reproduce this and it's been > 2 weeks since my last comment so I'm going to close this. @dunstn if you are still seeing an issue here feel free to re-open or create a new issue. Thanks!

**Closed by jasonmunro** 2018-11-15 19:35 UTC
Labels: awaiting feedback
