### ISSUE TITLE
🐛 [Compose] Detaching & Reattaching of files does not work

### ISSUE THREAD

**Issue by ulfgebhardt** [jasonmunro/cypht#323] opened 2019-03-06 12:06 UTC
### [Compose] Detaching & Reattaching of files does not work
Consider following Situation:
- You want to send a File and start writing the EMail and attach the File
- Now you notice there is a mistake in the File while writing
- You correct the Mistake, detach the file, and try to reattach it.
- The File does not appear, you have the start another compose

This is probl. the case since the file name has not changed.
(I did not try with a changed filename)

### Version & Environment

Rev: [70a3d129f0493d7885176040b39a69d51c422921](https://github.com/jasonmunro/cypht/commit/70a3d129f0493d7885176040b39a69d51c422921)

OS:  [Debian]

### Steps to reproduce
1. Attach File
2. Detach File
3. Reattach same File (or changed File with same name/path)
4. ...
5. Profit

**Comment by jasonmunro** [comment] 2019-03-20 22:21
This appears to be a Javascript bug as the second attempt to attach the file never triggers a server side request. I think the problem is using a change event as part of the flow. Re-uploading the same file is not a change in state so it never triggers the actual upload. I will let you know when I have a fix.

**Comment by jasonmunro** [comment] 2019-03-20 22:40
Should be fixed in the master branch

**Comment by jasonmunro** [comment] 2019-07-03 01:18
@ulfgebhardt I believe this is fixed so I'm closing this issue. If you are still seeing issues please re-open. Thanks!

**Closed by jasonmunro** 2019-07-03 01:18 UTC
Labels: awaiting feedback, bug, smtp

**Comment by ulfgebhardt** [comment] 2019-07-03 15:01
Hey @jasonmunro i am sorry that i did not respond in a timely manner - haven't updated cypht in quite some time. <3

**Comment by marclaporte** [comment] 2021-03-17 15:01
Related: https://github.com/jasonmunro/cypht/issues/421

**Comment by marclaporte** [comment] 2021-03-17 15:02
@ulfgebhardt Please retest with latest code.

Thanks!

**Comment by ulfgebhardt** [comment] 2021-03-17 17:01
@marclaporte I will in time, I still work with quite the old version of cypht. Will update some day I guess <3
