### ISSUE TITLE
compose:markdown icons missing

### ISSUE THREAD

**Issue by zeigerpuppy** [jasonmunro/cypht#305] opened 2018-11-26 09:34 UTC
## Issue
With the current version of cypht, I am having difficulty seeing the icons is the compose toolbar for Markdown.

![screenshot from 2018-11-26 20-31-14](https://user-images.githubusercontent.com/415981/49005242-58279400-f1ba-11e8-8ef9-ab648dda4e05.png)

The web server logs show this error
```
[:error]  PHP Notice:  Uninitialized string offset: 0 in /mnt/cypht/modules/core/message_functions.php on line 269, referer: http://cypht.server.net/?page=compose
```

- There are no errors in the browser console log (Debian 9 Firefox).
- The site is served locally for testing at the moment via a very simple apache config.
- Memcached is enabled and settings are in flat files at the moment.

```
<Virtualhost *:80>
ServerName cypht.server.net

    DocumentRoot /var/www/cypht
    <Directory />
        Options FollowSymLinks
        AllowOverride None
    </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

</Virtualhost>
```

**Comment by jasonmunro** [comment] 2018-11-27 17:20
@zeigerpuppy the warning is an unrelated issue that I will fix shortly. I can confirm that the issue is that we are forcing a global font in the theme CSS which is breaking the font based icons in the markdown editor. I will update here when I have a fix. Thanks for the feedback!

**Comment by jasonmunro** [comment] 2018-11-27 19:09
@zeigerpuppy should be fixed in the master branch. It's a css change so you will need to rerun the config gen script to recreate the production site.css file.

**Comment by jasonmunro** [comment] 2018-11-29 17:40
Thanks for the follow up and for checking out the markdown feature - not sure anybody but myself has tried it! :)

**Closed by jasonmunro** 2018-11-29 17:40 UTC
Labels: awaiting feedback, bug, smtp
